env:
  node: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier

rules:
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
