version: '3.9'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: k1tikurisu/research:base
    container_name: base
    working_dir: /works
    tty: true
    ports:
      - 4567:4567
    volumes:
      - type: bind
        source: .
        target: /works
      - type: bind
        source: ./scripts/opt/jsparser
        target: /opt/jsparser/jsparser
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: node_modules
        target: /works/node_modules
      - type: volume
        source: build
        target: /works/lib

volumes:
  node_modules:
  build:
