version: '3.9'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: daaiki/research:base
    container_name: base
    command: bash -c "./scripts/ssh_to_brain.sh"
    working_dir: /works
    tty: true
    volumes:
      - type: bind
        source: .
        target: /works
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/.ssh
        target: /root/.ssh
      - type: volume
        source: node_modules
        target: /works/node_modules
      - type: volume
        source: build
        target: /works/lib

volumes:
  node_modules:
  build:
